-- SQLite
SELECT TICKER, MAX(DATE), SETTLEMENT_DATE
FROM OIL_FUTURES_YAHOO
GROUP BY TICKER
ORDER BY SETTLEMENT_DATE;

WITH TEMP AS (
SELECT TICKER, MIN(DATE), SETTLEMENT_DATE
FROM OIL_FUTURES_YAHOO
GROUP BY TICKER
ORDER BY SETTLEMENT_DATE
)

SELECT * FROM TEMP;

SELECT * FROM OIL_FUTURES_YAHOO;


WITH TEMP_0 AS (
    SELECT DATE, TICKER, CLOSE
    FROM OIL_FUTURES_YAHOO
    --WHERE DATE = '{next_settelment_date_0}'
    --AND TICKER = 'CLN2022.NYM'
    WHERE TICKER = 'CLN22.NYM'

),
TEMP_3 AS (
    SELECT DATE, TICKER, CLOSE
    FROM OIL_FUTURES_YAHOO
    --WHERE DATE = '{next_settelment_date_3}'
    --AND TICKER = 'CLV2022.NYM'
    WHERE TICKER = 'CLV22.NYM'


)

SELECT 
    TEMP_0.DATE, TEMP_0.TICKER TICKER_0, TEMP_0.CLOSE CLOSE_0,
    TEMP_0.TICKER TICKER_3, TEMP_0.CLOSE CLOSE_3
FROM TEMP_0
JOIN TEMP_3
    ON TEMP_0.DATE = TEMP_3.DATE

-- DELETE FROM OIL_FUTURES_YAHOO;


SELECT DATE, SPR_FRONT_CONTRACT, SPR_FRONT_CLOSING, SPR_3MO_CONTRACT, SPR_3MO_CLOSING, SPR_6MO_CONTRACT, SPR_6MO_CLOSING, SPR_9MO_CONTRACT, SPR_9MO_CLOSING, SPR_12MO_CONTRACT, SPR_12MO_CLOSING
FROM OIL_FUTURES_CL_TIME_SPREADS;

--DELETE FROM OIL_FUTURES_CL_TIME_SPREADS;